/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultilingualAiPhoneAgentRouteImport } from './routes/multilingual-ai-phone-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultilingualAiPhoneAgentRoute =
  MultilingualAiPhoneAgentRouteImport.update({
    id: '/multilingual-ai-phone-agent',
    path: '/multilingual-ai-phone-agent',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/multilingual-ai-phone-agent': typeof MultilingualAiPhoneAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multilingual-ai-phone-agent': typeof MultilingualAiPhoneAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/multilingual-ai-phone-agent': typeof MultilingualAiPhoneAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/multilingual-ai-phone-agent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/multilingual-ai-phone-agent'
  id: '__root__' | '/' | '/multilingual-ai-phone-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MultilingualAiPhoneAgentRoute: typeof MultilingualAiPhoneAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multilingual-ai-phone-agent': {
      id: '/multilingual-ai-phone-agent'
      path: '/multilingual-ai-phone-agent'
      fullPath: '/multilingual-ai-phone-agent'
      preLoaderRoute: typeof MultilingualAiPhoneAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MultilingualAiPhoneAgentRoute: MultilingualAiPhoneAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
